sudo: false
language: java
jdk:
- oraclejdk8
- oraclejdk9
- oraclejdk10
jobs:
  include:
  - stage: deploy
    jdk: oraclejdk8
    script:
    - "./scripts/travis_decrypt_signing_key.sh"
    - "./scripts/mvn_deploy.sh"
    - "./scripts/mvn_upload_api_docs.sh"
script: make default
env:
  global:
  - secure: aRFxj6cdqo5QiKfv+I5hrxA2smdoFYZJehh3cK/mnUywAi3cJBv8mwokmBYxbGIeMAOMkjQFLsdkvoai511E0UDvRx6LrJmBRxWyWcLv/xaKzaVN+0Ova7VO67Y8DDj2JKU8QZGTUxl6tsDgaO4GFZUI56eL/VvKhEcU+wWGMJX9NMwdmpT2QNyFe/oCPmBuBSQy9bU4WDrpKWsZmApOca54wkhzz35Ve0Dx7R4aHOaXGRXNHh1g3epnukMuobAplLm2YWytJuvn9iG4C9JIx2IWkuF+VLvn4zsIwQs2bblgZhdtxw0nJUAe2yAKZXqwaesz3FoEK4ne3PNR53P3D4uOs8T3Dxv9HNN+05a3dD4r/2UWfc/JOXuxQar4ALhvV5cT/QgNEvezoXmQ17lVTG4IbZgNspU0P6Wz5y8sk0yqfrm5HAHCwfNs2SvoDE/nlLMCGeIhZBp4MEkqwDJuO0IeRtrzu0lyLgJUJSuNv50xivD8/+s/AW2W3H2yonAdzYhB/fN08C3dRLocO6+PSkvEQIr0DgDZ8lmeKCizbxdOUXc5uBQy2vgPTF4StW8637E8a+LkQdTP7Iy/cq1pP5PzTeY4tRSGElFx9VLBHWVZTZOgrMN6ixYRbRPEAD5qUvyiwl7VlUeXNNAKrYRclPc9tzXA+rVDB26C2/IYn08=
  - secure: mIB/NNmJ0MuHyUu1noif8+dT6sWyuoQAMch336R8bJzfg1UatkRcVrT156K/vRMjIznnJNFQZcH4S2Uj1/QLJSp5qLxV4c/B3aEq/nbxRb+OeMuXnpcMdwCGN57wqDogYd9Kdtw9kNcMywjy79jvu1l4iKg3NGVmdeglWcZrHAvKtykC1/KG7ctiSFI6632BBbbrIUuHAflyibxemXrriZegghQjvwe8xM78lQIuqiwWLkvNl6G/32PynATADEZhv2TJkSmGB1tk2t9j9TxlxGW7XTaXq+4ZHOyhVVc8vMhQFXpEElmJDlmlMgSYWR8NMglG+sx7JBkN4xZteqwqw59poYarp5L4BNFKV70DibjlhBGIjpdj+YWKWABxC/Jto+ZHNUSex669jmprRb2/djbmkOFsrhpOUWP1GJOmcFdTAObdg4eqbQTT1yC6Vnkv2wDm7LqdGZ1OlrA4nDHtKbe4Gbt5Q7h8oZpacq81OIqDQ2Z+RAtmqjPUq27W0dbLPfq/zd6MZtCbadFFlHvPQD98oqvti82RJJ8zWejcWdZuN9taFBBBiBh4BhGBlvAcYoPGaYiQ96BbOqmF+EL7p8Npl+M2s4GOF5QB41nRi7DZZhz05lGafTyMFt0DtVLHGFp6K1ur2Y4ApYHIULKvo5tIVyLz9bYWvbWIwD4zveM=
